### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by rodolfobandeira** [phpcanada/phpcanada#2]
Last time I checked, FOSUserBundle was not compatible with Symfony 3.

1) Should we use another authentication bundle or create another one from scratch?

**Comment by zrod** [comment]
It does work, if you use the dev-master branch:

https://packagist.org/packages/friendsofsymfony/user-bundle#dev-master

**Comment by rodolfobandeira** [comment]
FOSUserBundle installed with commit: 7d9d3e5109cb22c9f5591ad4f8c9f88a56d62636
